INSTRUCTIONS.txt
download-model.bat
install.bat
micromamba-cmd.bat
start-webui.bat

Will allow automatic install and usage of the current webui using only Micromamba. May need more extensive testing as CMD is buggy and temperamental with file paths. It seems to work well enough for Windows 10 and 11: https://github.com/oobabooga/text-generation-webui/issues/520
Currently incorporates [oobabooga-one-click-bandaid](https://github.com/ClayShoaf/oobabooga-one-click-bandaid)

Update one-click-installer for Windows

---

INSTRUCTIONS.txt
install.bat

- **Have pip directly download and install backup GPTQ wheel instead of first downloading through curl.**
- **Install bitsandbytes from wheel compiled for Windows from modified source.**
Compiled using: https://github.com/acpopescu/bitsandbytes/tree/cmake_windows
Hopefully, this will eliminate the need for hacky patches that seem to be a common failure point.
Also limits the use of curl which seems to have issues with some higher-security networks.
- **Add clarification of minor, intermittent issue to instructions.**
During testing, bitsandbytes would sometimes detect the wrong cuda version and fail because of it. It would detect the correct version when tried a second time. This may be an issue with my system as I have multiple versions of the cuda toolkit installed.
- **Add system32 …

Attempt to Improve Reliability

---

install.bat

Disables SSL certificate verification which was causing curl to fail on some systems. https://github.com/oobabooga/text-generation-webui/issues/644#issuecomment-1493518391

Add -k flag to curl command

---

install.bat

Figured out how to target a specific build of a conda package. Should prevent any further cases of the cpu version of torch getting randomly installed. Currently, this is only documented in the source code of conda.
- **Specifically target cuda 11.7 ver. of torch 2.0.0**
- **Move conda-forge channel to global list of channels**
- **Hopefully prevents missing or incorrect packages**
- **Add additional sanity check**
- **Add environment creation error**
- **Improve error visibility**

Prevent CPU version of Torch from being installed

---

install.bat

Following https://github.com/abetlen/llama-cpp-python/issues/40 I created PR https://github.com/abetlen/llama-cpp-python/pull/50, tested using "llama-13b-pretrained-sft-do2-4bit-128g.safetensors" installing from scratch multiple times.
While waiting for that PR to be merged you can test it by swapping for my fork temporarily. 
--no-deps is an artifact from testing, it is likely to work without it.

Add working llamaa-cpp-python install from wheel.

---

install.bat

[Loufe's pull request](https://github.com/oobabooga/one-click-installers/pull/13) was not ready to be merged yet.
@abetlen has not yet updated his repo to include wheels. As a temporary measure I have changed the link to the llama-cpp-python wheel to point to Loufe's fork.
- Correct llama-cpp-python wheel link
- Ensure that the path warning is actually seen

Correct llama-cpp-python wheel link

---

install.bat
start-webui.bat

llama-cpp-python now has wheels being built automatically and posted the their releases section.
So long as you keep the version in requirements.txt the same as the wheel, you should be able to safely add it back in.
The wheel version in the script is **`0.1.30`**
You could also just put the wheel url directly into the requirements.txt like so:
```
bitsandbytes==0.37.2; platform_system != "Windows"
llama-cpp-python==0.1.30; platform_system != "Windows"
https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.30/llama_cpp_python-0.1.30-cp310-cp310-win_amd64.whl; platform_system == "Windows"
```
In that case, there would be no need for the installer to download the wheel and you would be able to more easily maintain versions. I did not include the bitsandbytes wheel in the example …

Update llama-cpp-python link to official wheel

---

start_linux.sh

For some machines $OS_ARCH returns aarch64 instead of ARM64,and as i see here this should fix it.

Fixed error when $OS_ARCH returns aarch64

---

cmd_windows.bat
start_windows.bat
update_windows.bat

The PATH fix for broken Windows installs needs to come before the use of `findstr` as that is an executable located in System32.
Didn't realize that before now.

Fix Windows PATH fix

---

webui.py

Found out that the Cuda Toolkit installed in the environment includes an executable that reports the compute capability of your GPU. This allows for installation of an older bitsandbytes for GPUs that are incompatible with the latest version. This can also allow for installing a version of GPTQ that is compatible with GPUs older than Pascal, though I have not done that here.
This will need to be tested on a system with multiple GPUs. Not very experienced with Python, but I believe it should work. With multiple GPUs, the program outputs comma-separated numbers: `61,75`
This also needs to be tested on Linux to ensure that it works there.
Fixes https://github.com/oobabooga/text-generation-webui/issues/2377
bitsandbytes Windows wheels are now compiled through GitHub Actions: …

Install older bitsandbytes on older gpus + fix llama-cpp-python issue

---

webui.py

It checks to see if the environment variable OOBABOOGA_FLAGS exists.
If it finds OOBABOOGA_FLAGS it sets CMD_FLAGS  to OOBABOOGA_FLAGS and tell the user that flags are being set by an environment variable instead of inline in webui.py.
If there is no OOBABOOGA_FLAGS it will skip and run as usual.

Adds functionality for user to set flags via environment variable

---

webui.py

The `g++ --version` output is unreliable (my machine has `gcc (Ubuntu 12.2.0-17ubuntu1) 12.2.0`) and the current string matching doesn't support GCC 13 (oobabooga/text-generation-webui/issues/2131).
So instead I copied the [same command that pytorch](https://github.com/pytorch/pytorch/blob/ecd79b1fef4ad8823781b715002ab221c7075732/torch/utils/cpp_extension.py#L349) uses and parse that to get the major version.

Parse g++ version instead of using string matching

---

INSTRUCTIONS-WSL.TXT
cmd_wsl.bat
generate_zips.sh
start_wsl.bat
update_wsl.bat
wsl.sh

This installer is designed to be run in Windows like the Windows installer by double-clicking the `start_wsl.bat` script. The installer will check to see if the `build-essential` package is installed and ready to use and provide installation instructions if it is not. In my testing, this was needed to compile `llama-cpp-python` and all C++ compilers installable through Conda did not work. An option to continue without `build-essential` is included just in case.
Due to the need for `LF` line endings in the `wsl.sh` script, and the fact that git converts them to `CRLF` by default, the `start_wsl.bat` script will convert the line endings when run.
When installing, `webui.py` is copied to the installation directory to be used as-is. If command-line flags are added to it in Windows, the copy …

Installer for WSL

---

webui.py

Windows Miniconda installer does not allow special characters in the installation path. Displays a warning message if detected.
Couldn't find a list of specific characters that it checks for.
Not too sure if detection is necessary or not. Could just display a message on Windows by default.
Checking for these characters: ```!#$%&()*+,;<=>?@[]^`{|}~```
This is a response to: https://github.com/oobabooga/text-generation-webui/issues/1351#issuecomment-1589924256

Check for special characters in installation path on Windows

---

cmd_macos.sh

Some MacOS versions of Bash do not support process substitution `<()` in the way that it is done here. A user on the Discord server encountered this as I was helping them with something.
Fortunately, it isn't necessary and the same effect can be achieved in the way that I have done it here.

Fix cmd_macos.sh

---

webui.py

Simple git clone when installed with NVIDIA option. `git pull` is used to update exllama if already cloned.
`assert_success` is not used to allow the command to fail and not block GPTQ-for-LLaMa installation.
Rest of the code afterwards is for GPTQ-for-LLaMa, so the GPTQ clone still uses `assert_success`.

Install exllama

---

start_linux.sh
start_macos.sh
start_windows.bat
webui.py
wsl.sh

Installation through Conda seems to be fairly unreliable. People have ended up with the CPU-only build of Pytorch far too many times, even when explicitly telling Conda to install the CUDA 11.7 build. There have also been instances where RWKV will not work with the Conda package.
Installing Pytorch through pip will allow for some initial groundwork for basic AMD ROCm support in the future.
Theoretically, it may also allow for out-of-the-box MPS (Metal) GPU acceleration in Pytorch on supported MacOS versions.
I don't think abandoning Conda altogether is an option as it is used to install CUDA Toolkit, Git and Python for systems that don't have those already.
What are your thoughts on this?
---
Included changes:
- Install Pytorch through pip instead of Conda
- Fix for an issue building …

Install Pytorch through pip instead of Conda

---

webui.py

This is causing the installer to not update Peft resulting in various issues. The most recent one being:
https://github.com/oobabooga/text-generation-webui/issues/2773

Workaround for Peft not updating their package version on the git repo

---

webui.py

New bnb does not need it.
Commented out in case it is needed in the futute.

Remove bitsandbytes compatibility workaround

---

start_windows.bat
webui.py

The check was not working as intended due to it taking place after it actually mattered. Didn't think of that when I added it.
Also ported the `print_big_message` function to batch for use here and in the future.
Usage syntax with examples:
```
set "MESSAGEVARIABLE="First line enclosed in quotes." "Second line enclosed in quotes with whole variable contents also enclosed." "Any number of lines supported.""
call :PrintBigMessage %MESSAGEVARIABLE%
call :PrintBigMessage "First line enclosed in quotes." "Second line enclosed in quotes with whole variable contents also enclosed." "Any number of lines supported."
call :PrintBigMessage "First line enclosed in quotes." %MESSAGEVARIABLE% "Can be mixed with variables."
*******************************************************************
* First line …
```

Move special character check to start script

---

webui.py

Your fork requires minimum compute of 6.0. Will install from [main cuda repo](https://github.com/qwopqwop200/GPTQ-for-LLaMa/tree/cuda) if fork not supported.
Also removed cuBLAS llama-cpp-python installation in preparation for https://github.com/oobabooga/text-generation-webui/commit/4b19b74e6c8d9c99634e16774d3ebcb618ba7a18

Add check for compute support for GPTQ-for-LLaMa

---

INSTRUCTIONS.TXT
webui.py

Requires the ROCm SDK version 5.4.2 or 5.4.3. I do not have an AMD GPU, so community testing will be needed.
Things added:
- Install ROCm version of Pytorch
- Install ROCm ExLlama module for AMD GPUs
- Use a ROCm-compatible fork of GPTQ-for-LLaMa
- [Source](https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm)
- Pre-compiled wheel is used if failed to build locally.
- Use a ROCm-compatible fork of AutoGPTQ on AMD GPUs with pre-compiled wheel
- [Source](https://github.com/jllllll/AutoGPTQ/tree/rocm) based on: [AutoGPTQ-rocm](https://github.com/are-we-gfx1100-yet/AutoGPTQ-rocm)
- Pre-compiled wheel is used if failed to build locally. This should hopefully improve compatibility.
- Add AMD GPU installation instructions to INSTRUCTIONS.TXT

Add AMD GPU support for Linux

---

webui.py

Actually fixes: https://github.com/oobabooga/one-click-installers/issues/95
Resolves: https://github.com/oobabooga/text-generation-webui/issues/3407
Conda was prioritizing the main channel, which has the broken package, over conda-forge.

Properly fix broken gcc_linux-64 package

---

generate_zips.sh
wsl.sh

Similar to how `webui.py` is handled, `CMD_FLAGS.txt` will be copied to the WSL installation directory.
The file can be edited in Windows and changes will be carried over. Changes to the file in WSL will be maintained until the Windows copy is changed.

Add CMD_FLAGS.txt functionality to WSL installer

---

webui.py

Allow comments in CMD_FLAGS.txt to allow things like this (blushing, yes this is my CMD_FLAGS.txt)
```
--api
--model=TheBloke_OpenOrca-Platypus2-13B-GPTQ_gptq-8bit-128g-actorder_True
--listen
--extensions dbh superbooga
```

feature: allow comments in CMD_FLAGS.txt
